---
- name: Install software-properties-common
  apt: package={{ item }}
  with_items: [ software-properties-common, python-pycurl ]
- name: Add Ansible repo
  apt_repository: repo='ppa:ansible/ansible' state=present
- name: Install Ansible
  apt: package=ansible state=latest
